### PR TITLE
Feature/tox

### PR DESCRIPTION
**Pull request by mbehrle**
Note: postgres tests are currently failing.

### CODE REVIEW

**Comment by sharoonthomas** [comment]
Awesome.

I think `.travis.yml` should now be updated to run using tox and each on a different environment

**Comment by sharoonthomas** [comment]
LGTM

**Comment by mbehrle** [comment]
* Sharoon Thomas: " Re: [nereid-webshop] Feature/tox (#283)" (Tue, 03 Feb 2015
  02:50:14 -0800):

> Awesome.
> 
> I think `.travis.yml` should now be updated to run using tox and each on a
> different environment

Done and all tests other than postgres tests should work.

BTW: Observed too late, that prakashpp also worked in the very same
direction...;)

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by sharoonthomas** [comment]
@mbehrle any idea why the build currently passes with postgres but fails when run on tox ?

**Comment by mbehrle** [comment]
* Sharoon Thomas: " Re: [nereid-webshop] Feature/tox (#283)" (Fri, 06 Feb 2015
  04:05:41 -0800):

> @mbehrle any idea why the build currently passes with postgres but fails when
> run on tox ?

From my memory: the postgres tests dont't run for me on any environment.
Seems it has to do something with different transaction handling. So no, no
idea:(  I myself hoped, you would have a quick clue... 
Currently a bit overloaded I will have to look at it later.
The initial move to add the test was to track down
https://github.com/openlabs/nereid-checkout/issues/84, which currently crashes
my test environments of nereid-webshop.

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by sharoonthomas** [comment]
Thanks @mbehrle . @prakashpp and me are taking a look at the failing tests now. It is likely to be a simple Transaction initiation problem. 

This is really helpful and especially the packaging test.

**Comment by sharoonthomas** [comment]
Thank you @mbehrle for this patch.

@prakashpp on us to fix the tests now.

**Comment by mbehrle** [comment]
* Sharoon Thomas: " Re: [nereid-webshop] Feature/tox (#283)" (Fri, 06 Feb 2015
  23:51:02 -0800):

> Thank you @mbehrle for this patch.
> 
> @prakashpp on us to fix the tests now.

Very much appreciated, thx!


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Pull request merged**
